version: '3.7'
services:
  redis:
    image: 'redis:5.0.5'
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - AIRFLOW__CORE__FERNET_KEY=81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs=
    logging:
      options:
        max-size: 10m
        max-file: "3"

  webserver:
    image: apache/airflow:1.10.10-python3.7
    restart: always
    entrypoint: ["/bin/bash", "-c"]
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - DB_HOST=postgres
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/1
      - AIRFLOW__CORE__FERNET_KEY=81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs=
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: ["/usr/bin/dumb-init -- /entrypoint initdb && airflow webserver"]
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    image: apache/airflow:1.10.10-python3.7
    restart: always
    depends_on:
      - redis
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/1
      - AIRFLOW__CORE__FERNET_KEY=81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs=
    ports:
      - "5555:5555"
    command: flower

  scheduler:
    image: apache/airflow:1.10.10-python3.7
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./:/opt/airflow/dags
    environment:
      - LOAD_EX=n
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/1
      - AIRFLOW__CORE__FERNET_KEY=81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs=
    command: scheduler

  worker:
    image: apache/airflow:1.10.10-python3.7
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./:/opt/airflow/dags
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/1
      - AIRFLOW__CORE__FERNET_KEY=81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs=
    command: worker